# Generated by Django 4.0.1 on 2022-02-14 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro_links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_inicial', models.CharField(max_length=150)),
                ('url_gerada', models.CharField(max_length=150)),
                ('titulo', models.CharField(max_length=50)),
                ('data', models.DateTimeField(default=datetime.datetime(2022, 2, 14, 14, 55, 40, 988877), verbose_name='Encontrado em: ')),
            ],
        ),
    ]
