# Generated by Django 4.0.1 on 2022-01-20 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroFilmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('sinopse', models.TextField()),
                ('duracao', models.CharField(max_length=5)),
                ('genero', models.CharField(max_length=15)),
                ('data', models.DateTimeField(default=datetime.datetime(2022, 1, 20, 10, 0, 5, 867078), verbose_name='Publicadoem')),
            ],
        ),
    ]
